version: '3.8'

services:
  postgresql:
    image: postgres:13-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: "Asia/Shanghai"
    volumes:
      - ./data:/var/lib/postgresql/data