version: '3.7'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: 'root'
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
