version: "2"
services:
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos
    restart: always
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    volumes:
    - ./logs/:/home/nacos/logs
    ports:
    - "8848:8848"
    - "9848:9848"
