version: '3.1'
services:
  mysql-master:
    image: mysql:5.7.22
    container_name: mysql-master
    ports:
      - 3416:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: root@admin
    volumes:
      - ./master/log:/var/log/mysql
      - ./master/conf/my.cnf:/etc/mysql/my.cnf
      - ./master/data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_general_ci'
      - '--max_connections=3000'
    networks:
      - msnet
  mysql-slave:
    image: mysql:5.7.22
    container_name: mysql-slave
    ports:
      - 3426:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: root@admin
    volumes:
      - ./slave/log:/var/log/mysql
      - ./slave/conf/my.cnf:/etc/mysql/my.cnf
      - ./slave/data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_general_ci'
      - '--max_connections=3000'
    networks:
      - msnet
networks:
  msnet:
    driver: bridge
