services:
  # 主节点的容器
  redis-server:
    image: redis:6.2.6
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      # 映射配置文件和数据目录
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    sysctls:
      # 必要的内核参数
      net.core.somaxconn: '511'
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  